### ISSUE TITLE
SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by Afindor** [SSSxCCC/SLIM-LFM-recommendation#1]
when I run your script, I got the error message:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
SystemError: NULL result without error in PyObject_Call

 could you please give me any suggestions? Thanks.

**Comment by SSSxCCC** [comment]
My script is written in Python3. According to your error message, you are using python2, you should change your Python environment to Python3.

**Comment by Afindor** [comment]
Thank you, it works.
